### ISSUE TITLE
Zipping Stamp overlap causes duplicate evidenceBase entries

### ISSUE THREAD

**Issue by jorisbontje** [patham9/ANSNA#21]
Thanks for creating some basic test coverage, this in helpful for various experimentations and to double check the implication.

I noticed that when both stamps have the same evidenceBase (ie {1, 2}); "making"/zipping them creates duplicate entries (ie {1, 1, 2, 2}). This seems unwanted to me and a waste of EvidentalBase.
Instead I'd expect the result to be {1, 2}.

**Comment by patham9** [comment]
Thank you for all your help, and more tests for FIFO, PriorityQueue etc. are on the way! :)

In this case: ANSNA (and NARS-alikes) are only allowed to perform a reasoning step when the evidental bases of the premises do not overlap. So we don't need to check it, because if there is no element in common in the premise's evidental bases, and also no duplicate element in the base of a premise, then the zipped version of both bases will also not contain a duplicate element.
